version: '3'
services:
  php:
    build:
      context: ./php/
    volumes:
      - ./nginx/www:/var/www

  nginx:
    image: nginx:latest
    ports:
      - 81:80
    volumes:
      - ./nginx/www:/var/www
      - ./nginx/core:/etc/nginx/conf.d

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root